##pdf模版以及文件保存根目录
file:
  template:
    root: D:\tmpfile\template
  save:
    root: D:\tmpfile
  image:
    default: D:\tmpfile\template\default.jpg

OBS:
  ak: 111
  sk: 111
  endPoint: 111

server:
  port: 10201
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 8
      worker: 256
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # redis配置
  redis:
    # 地址
    host: r-m5e4k2hn8ewqc2wxlspd.redis.rds.aliyuncs.com
    # 端口，默认为6379
    port: 6379
    # 密码
    password: xinkao@2019
    # 连接超时时间
    timeout: 3s
    # jedis配置
    jedis:
      pool:
        max-active: 30
        min-idle: 5
        max-idle: 10
        max-wait: 3s
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.9.129.215:3306/hz_asset?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: b735c7b3d1f69a37
    druid:
      # 开启web监控
      web-stat-filter:
        enabled: true
      # 监控页面
      stat-view-servlet:
        enabled: true
        login-username: xinkao
        login-password: 123456
        url-pattern: /druid/*
        # 设置白名单，不填则允许所有访问
        allow:
      # 初始连接数
      initialSize: 3
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat,wall
      filter:
        wall:
          config:
            multi-statement-allow: true
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
  servlet:
    multipart:
      #单个文件最大为50M
      max-file-size: 50MB
      #单次请求文件总数大小为50M
      max-request-size: 50MB
# 日志配置
logging:
  level:
    com.xinkao: debug
    org.springframework: warn

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
##钉钉告警
dingtalk:
  alarm:
    enabled: false
    url:

ding:
  APPKEY: 111
  APPSCERET: 111-2rwT8vp
  CORPID: 111
  TOKENKEY: 111

monitor:
  APPKEY: 111
  APPSCERET: 111
  APPURL: 111

ipurl:
  url: http://127.0.0.1:10201

path:
  qrcode: D:/hz_asset/qrCode/